---
codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2

coverage:
  precision: 1
  round: down
  range: "85...100"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  after_n_builds: 2
